version : "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '5000:5000'
    volumes:
      - mydata:/app/data
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - mydata:/app/data
    stdin_open: true
    tty: true
    networks:
      - mynetwork
    depends_on:
      - backend


volumes:
  mydata:
    driver: local

networks:
  mynetwork:
    driver: bridge
     

  

