version : "3.8"
services:
  frontend:
    build: ./frontend/src
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - ./app/node_modules

